### ISSUE TITLE
关于Bin

### ISSUE THREAD

**Issue by tary** [hxhb/ue4-export-nav-data#4]
我记得UE的Recast是他们魔改的, 请问这样直接导出的bin 用其他的实现比如go-detour不能直接用吧, 我们导出的方法基本也一样, 但是是导出 obj 再用RecastCreator转bin

**Comment by hxhb** [comment]
我的另一个项目，是从UE里提取出来的recast，可以配套使用插件导出的Bin数据。[ue4-recast-detour](https://github.com/hxhb/ue4-recast-detour)

**Comment by tary** [comment]
[ue4-recast-detour](https://github.com/hxhb/ue4-recast-detour) 这个是基于哪个版本提取的呢

**Comment by hxhb** [comment]
最新的是4.26。
